name: Generic Docker Workflow
on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME_SHORT: {{ cookiecutter.project_category }}/{{ cookiecutter.pypi_package_name }}

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      checks: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build test image
        uses: gorilla-ai/devops-github-shared-actions/actions/build-push-docker@0.0.1
        id: build_test_image
        with:
          gcrw_host: {% raw %}${{ vars.GCRW_HOST }}{% endraw %}
          gcr_host: {% raw %}${{ vars.GCR_HOST }}{% endraw %}
          registry_username: {% raw %}${{ secrets.CUSTOM_REGISTRY_USERNAME }}{% endraw %}
          registry_password: {% raw %}${{ secrets.CUSTOM_REGISTRY_PASSWORD }}{% endraw %}
          image_name_short: {% raw %}${{ env.IMAGE_NAME_SHORT }}{% endraw %}
          load: true
          target: test-build
          tags: {% raw %}${{ env.IMAGE_NAME_SHORT }}:test-build{% endraw %}
          fail_if_trivy_fails: 0

      - name: Run unit tests (pytest)
        run: |
          docker run -v /tmp:/app/reports --rm {% raw %}${{ env.IMAGE_NAME_SHORT }}:test-build{% endraw %}
          cp /tmp/pytest.xml pytest.xml
          cp /tmp/pytest-coverage.txt pytest-coverage.txt

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: success() || failure() # always run even if the previous step fails
        with:
          files: |
            pytest.xml

      - name: Pytest coverage comment
        if: success() || failure() # always run even if the previous step fails
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          title: Coverage Report
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
          github-token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
          hide-comment: {% raw %}${{ github.event_name != 'pull_request' }}{% endraw %}

      - name: Update job summary with coverage report
        if: success() || failure() # always run even if the previous step fails
        run: |
          echo "{% raw %}${{ steps.coverageComment.outputs.coverageHtml }}{% endraw %}" >> $GITHUB_STEP_SUMMARY

      - name: Build docker image
        uses: gorilla-ai/devops-github-shared-actions/actions/build-push-docker@0.0.1
        id: build_image
        with:
          gcrw_host: {% raw %}${{ vars.GCRW_HOST }}{% endraw %}
          gcr_host: {% raw %}${{ vars.GCR_HOST }}{% endraw %}
          registry_username: {% raw %}${{ secrets.CUSTOM_REGISTRY_USERNAME }}{% endraw %}
          registry_password: {% raw %}${{ secrets.CUSTOM_REGISTRY_PASSWORD }}{% endraw %}
          image-name-short: {% raw %}${{ env.IMAGE_NAME_SHORT }}{% endraw %}
          push: true
          fail_if_trivy_fails: 0
